/* tslint:disable */
/* eslint-disable */
/**
 * NeuroVerify Detection API
 * AI-generated and manipulated media detection for images and video.  NeuroVerify scores uploaded media for signs of spoofing and AI manipulation and returns an opaque risk score with a risk band, so you can accept, review, or reject without handling model internals.  **Authentication.** Send your API key in the `x-api-key` header on every request.  **Response envelopes.** Each endpoint wraps its result in a single named object, and that envelope is returned for successes, rejections, and errors alike. Read `status` and `status_code` to tell them apart rather than relying on the HTTP status code alone: a rejection for no face detected arrives as HTTP 200.  **Retries.** Retry HTTP 500 and 503 with exponential backoff, up to three attempts. Retry HTTP 429 after the interval given in `Retry-After`. Do not retry HTTP 400 or 401; correct the input or the key instead.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@neuraldefend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiError,
  DetectImageResponse,
} from '../models/index';
import {
    ApiErrorFromJSON,
    ApiErrorToJSON,
    DetectImageResponseFromJSON,
    DetectImageResponseToJSON,
} from '../models/index';

export interface DetectImageRequest {
    file: Blob;
}

/**
 * 
 */
export class ImageAuthenticityApi extends runtime.BaseAPI {

    /**
     * Analyzes a single-face image and returns an opaque authenticity risk score with a risk band and a human-readable message.  **Requirements.** JPEG, PNG, BMP, TIFF, WebP, or HEIC. Maximum 10 MB, minimum 224x224 pixels, exactly one face. EXIF rotation is corrected automatically. Images with no face or several faces return `status: \"rejected\"` on HTTP 200 and are billable.  **Reading the result.** Branch on `status` first, then apply business rules to `risk_level` rather than to `risk_score`, since band thresholds may be tuned.  Every request produces a new `unique_trx_id`; requests are not idempotent.
     * Score the authenticity of a face image
     */
    async detectImageRaw(requestParameters: DetectImageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DetectImageResponse>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling detectImage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/detect/image`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DetectImageResponseFromJSON(jsonValue));
    }

    /**
     * Analyzes a single-face image and returns an opaque authenticity risk score with a risk band and a human-readable message.  **Requirements.** JPEG, PNG, BMP, TIFF, WebP, or HEIC. Maximum 10 MB, minimum 224x224 pixels, exactly one face. EXIF rotation is corrected automatically. Images with no face or several faces return `status: \"rejected\"` on HTTP 200 and are billable.  **Reading the result.** Branch on `status` first, then apply business rules to `risk_level` rather than to `risk_score`, since band thresholds may be tuned.  Every request produces a new `unique_trx_id`; requests are not idempotent.
     * Score the authenticity of a face image
     */
    async detectImage(requestParameters: DetectImageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DetectImageResponse> {
        const response = await this.detectImageRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
