/* tslint:disable */
/* eslint-disable */
/**
 * NeuroVerify Detection API
 * AI-generated and manipulated media detection for images and video.  NeuroVerify scores uploaded media for signs of spoofing and AI manipulation and returns an opaque risk score with a risk band, so you can accept, review, or reject without handling model internals.  **Authentication.** Send your API key in the `x-api-key` header on every request.  **Response envelopes.** Each endpoint wraps its result in a single named object, and that envelope is returned for successes, rejections, and errors alike. Read `status` and `status_code` to tell them apart rather than relying on the HTTP status code alone: a rejection for no face detected arrives as HTTP 200.  **Retries.** Retry HTTP 500 and 503 with exponential backoff, up to three attempts. Retry HTTP 429 after the interval given in `Retry-After`. Do not retry HTTP 400 or 401; correct the input or the key instead.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@neuraldefend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiError,
  DetectVideoResponse,
} from '../models/index';
import {
    ApiErrorFromJSON,
    ApiErrorToJSON,
    DetectVideoResponseFromJSON,
    DetectVideoResponseToJSON,
} from '../models/index';

export interface DetectVideoRequest {
    file: Blob;
    maxFrames?: number | null;
    sampleRate?: number | null;
}

/**
 * 
 */
export class VideoAuthenticityApi extends runtime.BaseAPI {

    /**
     * Analyzes a video and returns independent risk scores for the video and audio modalities, each with its own risk band and message.  **Requirements.** MP4, AVI, MOV, MKV, WMV, FLV, WebM, OGG, or OGV. Maximum 1.5 GB. Frames are sampled uniformly, 12 by default. Frames containing several faces are skipped; if no single-face frames remain, the response is a rejection with `status_code: 6` on HTTP 200, and it is billable.  **Reading the result.** Video and audio are scored separately and no combined score is returned. Derive one client-side when you need it, for example max(video_risk_score, audio_risk_score or 0). Silent videos return null audio scores with `audio_message` set to \"No audio track detected\"; this is a success, not an error.  Every request produces a new `unique_trx_id`; requests are not idempotent.
     * Score the authenticity of a video and its audio track
     */
    async detectVideoRaw(requestParameters: DetectVideoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DetectVideoResponse>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling detectVideo().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['maxFrames'] != null) {
            queryParameters['max_frames'] = requestParameters['maxFrames'];
        }

        if (requestParameters['sampleRate'] != null) {
            queryParameters['sample_rate'] = requestParameters['sampleRate'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/detect/video`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DetectVideoResponseFromJSON(jsonValue));
    }

    /**
     * Analyzes a video and returns independent risk scores for the video and audio modalities, each with its own risk band and message.  **Requirements.** MP4, AVI, MOV, MKV, WMV, FLV, WebM, OGG, or OGV. Maximum 1.5 GB. Frames are sampled uniformly, 12 by default. Frames containing several faces are skipped; if no single-face frames remain, the response is a rejection with `status_code: 6` on HTTP 200, and it is billable.  **Reading the result.** Video and audio are scored separately and no combined score is returned. Derive one client-side when you need it, for example max(video_risk_score, audio_risk_score or 0). Silent videos return null audio scores with `audio_message` set to \"No audio track detected\"; this is a success, not an error.  Every request produces a new `unique_trx_id`; requests are not idempotent.
     * Score the authenticity of a video and its audio track
     */
    async detectVideo(requestParameters: DetectVideoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DetectVideoResponse> {
        const response = await this.detectVideoRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
