/*
NeuroVerify Detection API

AI-generated and manipulated media detection for images and video.  NeuroVerify scores uploaded media for signs of spoofing and AI manipulation and returns an opaque risk score with a risk band, so you can accept, review, or reject without handling model internals.  **Authentication.** Send your API key in the `x-api-key` header on every request.  **Response envelopes.** Each endpoint wraps its result in a single named object, and that envelope is returned for successes, rejections, and errors alike. Read `status` and `status_code` to tell them apart rather than relying on the HTTP status code alone: a rejection for no face detected arrives as HTTP 200.  **Retries.** Retry HTTP 500 and 503 with exponential backoff, up to three attempts. Retry HTTP 429 after the interval given in `Retry-After`. Do not retry HTTP 400 or 401; correct the input or the key instead.

API version: 1.0.0
Contact: support@neuraldefend.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package core

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DetectImageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DetectImageResponse{}

// DetectImageResponse Envelope returned by POST /detect/image for every outcome.
type DetectImageResponse struct {
	UnifiedFaceAuthenticityScore UnifiedFaceAuthenticityScore `json:"unified_face_authenticity_score"`
}

type _DetectImageResponse DetectImageResponse

// NewDetectImageResponse instantiates a new DetectImageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDetectImageResponse(unifiedFaceAuthenticityScore UnifiedFaceAuthenticityScore) *DetectImageResponse {
	this := DetectImageResponse{}
	this.UnifiedFaceAuthenticityScore = unifiedFaceAuthenticityScore
	return &this
}

// NewDetectImageResponseWithDefaults instantiates a new DetectImageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDetectImageResponseWithDefaults() *DetectImageResponse {
	this := DetectImageResponse{}
	return &this
}

// GetUnifiedFaceAuthenticityScore returns the UnifiedFaceAuthenticityScore field value
func (o *DetectImageResponse) GetUnifiedFaceAuthenticityScore() UnifiedFaceAuthenticityScore {
	if o == nil {
		var ret UnifiedFaceAuthenticityScore
		return ret
	}

	return o.UnifiedFaceAuthenticityScore
}

// GetUnifiedFaceAuthenticityScoreOk returns a tuple with the UnifiedFaceAuthenticityScore field value
// and a boolean to check if the value has been set.
func (o *DetectImageResponse) GetUnifiedFaceAuthenticityScoreOk() (*UnifiedFaceAuthenticityScore, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnifiedFaceAuthenticityScore, true
}

// SetUnifiedFaceAuthenticityScore sets field value
func (o *DetectImageResponse) SetUnifiedFaceAuthenticityScore(v UnifiedFaceAuthenticityScore) {
	o.UnifiedFaceAuthenticityScore = v
}

func (o DetectImageResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DetectImageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["unified_face_authenticity_score"] = o.UnifiedFaceAuthenticityScore
	return toSerialize, nil
}

func (o *DetectImageResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"unified_face_authenticity_score",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDetectImageResponse := _DetectImageResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDetectImageResponse)

	if err != nil {
		return err
	}

	*o = DetectImageResponse(varDetectImageResponse)

	return err
}

type NullableDetectImageResponse struct {
	value *DetectImageResponse
	isSet bool
}

func (v NullableDetectImageResponse) Get() *DetectImageResponse {
	return v.value
}

func (v *NullableDetectImageResponse) Set(val *DetectImageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDetectImageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDetectImageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDetectImageResponse(val *DetectImageResponse) *NullableDetectImageResponse {
	return &NullableDetectImageResponse{value: val, isSet: true}
}

func (v NullableDetectImageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDetectImageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


