/*
NeuroVerify Detection API

AI-generated and manipulated media detection for images and video.  NeuroVerify scores uploaded media for signs of spoofing and AI manipulation and returns an opaque risk score with a risk band, so you can accept, review, or reject without handling model internals.  **Authentication.** Send your API key in the `x-api-key` header on every request.  **Response envelopes.** Each endpoint wraps its result in a single named object, and that envelope is returned for successes, rejections, and errors alike. Read `status` and `status_code` to tell them apart rather than relying on the HTTP status code alone: a rejection for no face detected arrives as HTTP 200.  **Retries.** Retry HTTP 500 and 503 with exponential backoff, up to three attempts. Retry HTTP 429 after the interval given in `Retry-After`. Do not retry HTTP 400 or 401; correct the input or the key instead.

API version: 1.0.0
Contact: support@neuraldefend.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package core

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UnifiedVideoAuthenticityScore type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnifiedVideoAuthenticityScore{}

// UnifiedVideoAuthenticityScore Video authenticity result with independent video and audio risk scores. Derive an overall decision client-side, for example max(video_risk_score, audio_risk_score or 0).
type UnifiedVideoAuthenticityScore struct {
	// Unique transaction identifier. Store it for audit trail correlation and dispute resolution.
	UniqueTrxId string `json:"unique_trx_id"`
	// Name of the uploaded file, as received.
	Filename string `json:"filename"`
	// MIME type detected for the uploaded file.
	ContentType string `json:"content_type"`
	// Outcome of the request. `success` means the file was scored. `rejected` means the file did not pass pre-analysis validation and was not scored. `error` means a server-side failure prevented analysis.
	Status string `json:"status"`
	// `Y` when the request counts toward billing, `N` otherwise.
	Billable string `json:"billable"`
	// 1 scored successfully (HTTP 200, billable). 2 input validation rejection (HTTP 400, not billable). 5 server-side error (HTTP 500 or 503, not billable). 6 no scorable single-face frames (HTTP 200, billable).
	StatusCode int32 `json:"status_code"`
	// Video modality risk from 0.1 to 10.0, where higher means a higher likelihood of AI manipulation. Null when the request was rejected or errored.
	VideoRiskScore NullableFloat32 `json:"video_risk_score"`
	// Video risk band: low is 0.1-3.9, medium is 4.0-6.9, high is 7.0-10.0. Null when the video was not scored.
	VideoRiskLevel NullableString `json:"video_risk_level"`
	// Human-readable explanation for the video modality. Rejection and error copy is carried on this field.
	VideoMessage string `json:"video_message"`
	// Audio modality risk from 0.1 to 10.0. Null when the video has no audio track, or when audio analysis was skipped or failed.
	AudioRiskScore NullableFloat32 `json:"audio_risk_score"`
	// Audio risk band, using the same thresholds as video. Null when the audio was not scored.
	AudioRiskLevel NullableString `json:"audio_risk_level"`
	// Human-readable explanation for the audio modality, such as \"No audio track detected\". Null on rejected requests.
	AudioMessage NullableString `json:"audio_message"`
	// Checks applied during analysis. Present only on scored responses.
	AiThreatSignals []string `json:"ai_threat_signals,omitempty"`
}

type _UnifiedVideoAuthenticityScore UnifiedVideoAuthenticityScore

// NewUnifiedVideoAuthenticityScore instantiates a new UnifiedVideoAuthenticityScore object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnifiedVideoAuthenticityScore(uniqueTrxId string, filename string, contentType string, status string, billable string, statusCode int32, videoRiskScore NullableFloat32, videoRiskLevel NullableString, videoMessage string, audioRiskScore NullableFloat32, audioRiskLevel NullableString, audioMessage NullableString) *UnifiedVideoAuthenticityScore {
	this := UnifiedVideoAuthenticityScore{}
	this.UniqueTrxId = uniqueTrxId
	this.Filename = filename
	this.ContentType = contentType
	this.Status = status
	this.Billable = billable
	this.StatusCode = statusCode
	this.VideoRiskScore = videoRiskScore
	this.VideoRiskLevel = videoRiskLevel
	this.VideoMessage = videoMessage
	this.AudioRiskScore = audioRiskScore
	this.AudioRiskLevel = audioRiskLevel
	this.AudioMessage = audioMessage
	return &this
}

// NewUnifiedVideoAuthenticityScoreWithDefaults instantiates a new UnifiedVideoAuthenticityScore object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnifiedVideoAuthenticityScoreWithDefaults() *UnifiedVideoAuthenticityScore {
	this := UnifiedVideoAuthenticityScore{}
	return &this
}

// GetUniqueTrxId returns the UniqueTrxId field value
func (o *UnifiedVideoAuthenticityScore) GetUniqueTrxId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UniqueTrxId
}

// GetUniqueTrxIdOk returns a tuple with the UniqueTrxId field value
// and a boolean to check if the value has been set.
func (o *UnifiedVideoAuthenticityScore) GetUniqueTrxIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UniqueTrxId, true
}

// SetUniqueTrxId sets field value
func (o *UnifiedVideoAuthenticityScore) SetUniqueTrxId(v string) {
	o.UniqueTrxId = v
}

// GetFilename returns the Filename field value
func (o *UnifiedVideoAuthenticityScore) GetFilename() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value
// and a boolean to check if the value has been set.
func (o *UnifiedVideoAuthenticityScore) GetFilenameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filename, true
}

// SetFilename sets field value
func (o *UnifiedVideoAuthenticityScore) SetFilename(v string) {
	o.Filename = v
}

// GetContentType returns the ContentType field value
func (o *UnifiedVideoAuthenticityScore) GetContentType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value
// and a boolean to check if the value has been set.
func (o *UnifiedVideoAuthenticityScore) GetContentTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentType, true
}

// SetContentType sets field value
func (o *UnifiedVideoAuthenticityScore) SetContentType(v string) {
	o.ContentType = v
}

// GetStatus returns the Status field value
func (o *UnifiedVideoAuthenticityScore) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UnifiedVideoAuthenticityScore) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UnifiedVideoAuthenticityScore) SetStatus(v string) {
	o.Status = v
}

// GetBillable returns the Billable field value
func (o *UnifiedVideoAuthenticityScore) GetBillable() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Billable
}

// GetBillableOk returns a tuple with the Billable field value
// and a boolean to check if the value has been set.
func (o *UnifiedVideoAuthenticityScore) GetBillableOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Billable, true
}

// SetBillable sets field value
func (o *UnifiedVideoAuthenticityScore) SetBillable(v string) {
	o.Billable = v
}

// GetStatusCode returns the StatusCode field value
func (o *UnifiedVideoAuthenticityScore) GetStatusCode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value
// and a boolean to check if the value has been set.
func (o *UnifiedVideoAuthenticityScore) GetStatusCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StatusCode, true
}

// SetStatusCode sets field value
func (o *UnifiedVideoAuthenticityScore) SetStatusCode(v int32) {
	o.StatusCode = v
}

// GetVideoRiskScore returns the VideoRiskScore field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *UnifiedVideoAuthenticityScore) GetVideoRiskScore() float32 {
	if o == nil || o.VideoRiskScore.Get() == nil {
		var ret float32
		return ret
	}

	return *o.VideoRiskScore.Get()
}

// GetVideoRiskScoreOk returns a tuple with the VideoRiskScore field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UnifiedVideoAuthenticityScore) GetVideoRiskScoreOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.VideoRiskScore.Get(), o.VideoRiskScore.IsSet()
}

// SetVideoRiskScore sets field value
func (o *UnifiedVideoAuthenticityScore) SetVideoRiskScore(v float32) {
	o.VideoRiskScore.Set(&v)
}

// GetVideoRiskLevel returns the VideoRiskLevel field value
// If the value is explicit nil, the zero value for string will be returned
func (o *UnifiedVideoAuthenticityScore) GetVideoRiskLevel() string {
	if o == nil || o.VideoRiskLevel.Get() == nil {
		var ret string
		return ret
	}

	return *o.VideoRiskLevel.Get()
}

// GetVideoRiskLevelOk returns a tuple with the VideoRiskLevel field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UnifiedVideoAuthenticityScore) GetVideoRiskLevelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VideoRiskLevel.Get(), o.VideoRiskLevel.IsSet()
}

// SetVideoRiskLevel sets field value
func (o *UnifiedVideoAuthenticityScore) SetVideoRiskLevel(v string) {
	o.VideoRiskLevel.Set(&v)
}

// GetVideoMessage returns the VideoMessage field value
func (o *UnifiedVideoAuthenticityScore) GetVideoMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VideoMessage
}

// GetVideoMessageOk returns a tuple with the VideoMessage field value
// and a boolean to check if the value has been set.
func (o *UnifiedVideoAuthenticityScore) GetVideoMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VideoMessage, true
}

// SetVideoMessage sets field value
func (o *UnifiedVideoAuthenticityScore) SetVideoMessage(v string) {
	o.VideoMessage = v
}

// GetAudioRiskScore returns the AudioRiskScore field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *UnifiedVideoAuthenticityScore) GetAudioRiskScore() float32 {
	if o == nil || o.AudioRiskScore.Get() == nil {
		var ret float32
		return ret
	}

	return *o.AudioRiskScore.Get()
}

// GetAudioRiskScoreOk returns a tuple with the AudioRiskScore field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UnifiedVideoAuthenticityScore) GetAudioRiskScoreOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AudioRiskScore.Get(), o.AudioRiskScore.IsSet()
}

// SetAudioRiskScore sets field value
func (o *UnifiedVideoAuthenticityScore) SetAudioRiskScore(v float32) {
	o.AudioRiskScore.Set(&v)
}

// GetAudioRiskLevel returns the AudioRiskLevel field value
// If the value is explicit nil, the zero value for string will be returned
func (o *UnifiedVideoAuthenticityScore) GetAudioRiskLevel() string {
	if o == nil || o.AudioRiskLevel.Get() == nil {
		var ret string
		return ret
	}

	return *o.AudioRiskLevel.Get()
}

// GetAudioRiskLevelOk returns a tuple with the AudioRiskLevel field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UnifiedVideoAuthenticityScore) GetAudioRiskLevelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AudioRiskLevel.Get(), o.AudioRiskLevel.IsSet()
}

// SetAudioRiskLevel sets field value
func (o *UnifiedVideoAuthenticityScore) SetAudioRiskLevel(v string) {
	o.AudioRiskLevel.Set(&v)
}

// GetAudioMessage returns the AudioMessage field value
// If the value is explicit nil, the zero value for string will be returned
func (o *UnifiedVideoAuthenticityScore) GetAudioMessage() string {
	if o == nil || o.AudioMessage.Get() == nil {
		var ret string
		return ret
	}

	return *o.AudioMessage.Get()
}

// GetAudioMessageOk returns a tuple with the AudioMessage field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UnifiedVideoAuthenticityScore) GetAudioMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AudioMessage.Get(), o.AudioMessage.IsSet()
}

// SetAudioMessage sets field value
func (o *UnifiedVideoAuthenticityScore) SetAudioMessage(v string) {
	o.AudioMessage.Set(&v)
}

// GetAiThreatSignals returns the AiThreatSignals field value if set, zero value otherwise.
func (o *UnifiedVideoAuthenticityScore) GetAiThreatSignals() []string {
	if o == nil || IsNil(o.AiThreatSignals) {
		var ret []string
		return ret
	}
	return o.AiThreatSignals
}

// GetAiThreatSignalsOk returns a tuple with the AiThreatSignals field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedVideoAuthenticityScore) GetAiThreatSignalsOk() ([]string, bool) {
	if o == nil || IsNil(o.AiThreatSignals) {
		return nil, false
	}
	return o.AiThreatSignals, true
}

// HasAiThreatSignals returns a boolean if a field has been set.
func (o *UnifiedVideoAuthenticityScore) HasAiThreatSignals() bool {
	if o != nil && !IsNil(o.AiThreatSignals) {
		return true
	}

	return false
}

// SetAiThreatSignals gets a reference to the given []string and assigns it to the AiThreatSignals field.
func (o *UnifiedVideoAuthenticityScore) SetAiThreatSignals(v []string) {
	o.AiThreatSignals = v
}

func (o UnifiedVideoAuthenticityScore) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnifiedVideoAuthenticityScore) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["unique_trx_id"] = o.UniqueTrxId
	toSerialize["filename"] = o.Filename
	toSerialize["content_type"] = o.ContentType
	toSerialize["status"] = o.Status
	toSerialize["billable"] = o.Billable
	toSerialize["status_code"] = o.StatusCode
	toSerialize["video_risk_score"] = o.VideoRiskScore.Get()
	toSerialize["video_risk_level"] = o.VideoRiskLevel.Get()
	toSerialize["video_message"] = o.VideoMessage
	toSerialize["audio_risk_score"] = o.AudioRiskScore.Get()
	toSerialize["audio_risk_level"] = o.AudioRiskLevel.Get()
	toSerialize["audio_message"] = o.AudioMessage.Get()
	if !IsNil(o.AiThreatSignals) {
		toSerialize["ai_threat_signals"] = o.AiThreatSignals
	}
	return toSerialize, nil
}

func (o *UnifiedVideoAuthenticityScore) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"unique_trx_id",
		"filename",
		"content_type",
		"status",
		"billable",
		"status_code",
		"video_risk_score",
		"video_risk_level",
		"video_message",
		"audio_risk_score",
		"audio_risk_level",
		"audio_message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUnifiedVideoAuthenticityScore := _UnifiedVideoAuthenticityScore{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUnifiedVideoAuthenticityScore)

	if err != nil {
		return err
	}

	*o = UnifiedVideoAuthenticityScore(varUnifiedVideoAuthenticityScore)

	return err
}

type NullableUnifiedVideoAuthenticityScore struct {
	value *UnifiedVideoAuthenticityScore
	isSet bool
}

func (v NullableUnifiedVideoAuthenticityScore) Get() *UnifiedVideoAuthenticityScore {
	return v.value
}

func (v *NullableUnifiedVideoAuthenticityScore) Set(val *UnifiedVideoAuthenticityScore) {
	v.value = val
	v.isSet = true
}

func (v NullableUnifiedVideoAuthenticityScore) IsSet() bool {
	return v.isSet
}

func (v *NullableUnifiedVideoAuthenticityScore) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnifiedVideoAuthenticityScore(val *UnifiedVideoAuthenticityScore) *NullableUnifiedVideoAuthenticityScore {
	return &NullableUnifiedVideoAuthenticityScore{value: val, isSet: true}
}

func (v NullableUnifiedVideoAuthenticityScore) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnifiedVideoAuthenticityScore) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


