/*
NeuroVerify Detection API

AI-generated and manipulated media detection for images and video.  NeuroVerify scores uploaded media for signs of spoofing and AI manipulation and returns an opaque risk score with a risk band, so you can accept, review, or reject without handling model internals.  **Authentication.** Send your API key in the `x-api-key` header on every request.  **Response envelopes.** Each endpoint wraps its result in a single named object, and that envelope is returned for successes, rejections, and errors alike. Read `status` and `status_code` to tell them apart rather than relying on the HTTP status code alone: a rejection for no face detected arrives as HTTP 200.  **Retries.** Retry HTTP 500 and 503 with exponential backoff, up to three attempts. Retry HTTP 429 after the interval given in `Retry-After`. Do not retry HTTP 400 or 401; correct the input or the key instead.

API version: 1.0.0
Contact: support@neuraldefend.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package core

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DetectVideoResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DetectVideoResponse{}

// DetectVideoResponse Envelope returned by POST /detect/video for every outcome.
type DetectVideoResponse struct {
	UnifiedVideoAuthenticityScore UnifiedVideoAuthenticityScore `json:"unified_video_authenticity_score"`
}

type _DetectVideoResponse DetectVideoResponse

// NewDetectVideoResponse instantiates a new DetectVideoResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDetectVideoResponse(unifiedVideoAuthenticityScore UnifiedVideoAuthenticityScore) *DetectVideoResponse {
	this := DetectVideoResponse{}
	this.UnifiedVideoAuthenticityScore = unifiedVideoAuthenticityScore
	return &this
}

// NewDetectVideoResponseWithDefaults instantiates a new DetectVideoResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDetectVideoResponseWithDefaults() *DetectVideoResponse {
	this := DetectVideoResponse{}
	return &this
}

// GetUnifiedVideoAuthenticityScore returns the UnifiedVideoAuthenticityScore field value
func (o *DetectVideoResponse) GetUnifiedVideoAuthenticityScore() UnifiedVideoAuthenticityScore {
	if o == nil {
		var ret UnifiedVideoAuthenticityScore
		return ret
	}

	return o.UnifiedVideoAuthenticityScore
}

// GetUnifiedVideoAuthenticityScoreOk returns a tuple with the UnifiedVideoAuthenticityScore field value
// and a boolean to check if the value has been set.
func (o *DetectVideoResponse) GetUnifiedVideoAuthenticityScoreOk() (*UnifiedVideoAuthenticityScore, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnifiedVideoAuthenticityScore, true
}

// SetUnifiedVideoAuthenticityScore sets field value
func (o *DetectVideoResponse) SetUnifiedVideoAuthenticityScore(v UnifiedVideoAuthenticityScore) {
	o.UnifiedVideoAuthenticityScore = v
}

func (o DetectVideoResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DetectVideoResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["unified_video_authenticity_score"] = o.UnifiedVideoAuthenticityScore
	return toSerialize, nil
}

func (o *DetectVideoResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"unified_video_authenticity_score",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDetectVideoResponse := _DetectVideoResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDetectVideoResponse)

	if err != nil {
		return err
	}

	*o = DetectVideoResponse(varDetectVideoResponse)

	return err
}

type NullableDetectVideoResponse struct {
	value *DetectVideoResponse
	isSet bool
}

func (v NullableDetectVideoResponse) Get() *DetectVideoResponse {
	return v.value
}

func (v *NullableDetectVideoResponse) Set(val *DetectVideoResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDetectVideoResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDetectVideoResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDetectVideoResponse(val *DetectVideoResponse) *NullableDetectVideoResponse {
	return &NullableDetectVideoResponse{value: val, isSet: true}
}

func (v NullableDetectVideoResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDetectVideoResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


