/*
NeuroVerify Detection API

AI-generated and manipulated media detection for images and video.  NeuroVerify scores uploaded media for signs of spoofing and AI manipulation and returns an opaque risk score with a risk band, so you can accept, review, or reject without handling model internals.  **Authentication.** Send your API key in the `x-api-key` header on every request.  **Response envelopes.** Each endpoint wraps its result in a single named object, and that envelope is returned for successes, rejections, and errors alike. Read `status` and `status_code` to tell them apart rather than relying on the HTTP status code alone: a rejection for no face detected arrives as HTTP 200.  **Retries.** Retry HTTP 500 and 503 with exponential backoff, up to three attempts. Retry HTTP 429 after the interval given in `Retry-After`. Do not retry HTTP 400 or 401; correct the input or the key instead.

API version: 1.0.0
Contact: support@neuraldefend.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package core

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UnifiedFaceAuthenticityScore type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnifiedFaceAuthenticityScore{}

// UnifiedFaceAuthenticityScore Face authenticity result for a single uploaded image.
type UnifiedFaceAuthenticityScore struct {
	// Unique transaction identifier. Store it for audit trail correlation and dispute resolution.
	UniqueTrxId string `json:"unique_trx_id"`
	// Name of the uploaded file, as received.
	Filename string `json:"filename"`
	// MIME type detected for the uploaded file.
	ContentType string `json:"content_type"`
	// Outcome of the request. `success` means the file was scored. `rejected` means the file did not pass pre-analysis validation and was not scored. `error` means a server-side failure prevented analysis.
	Status string `json:"status"`
	// `Y` when the request counts toward billing, `N` otherwise.
	Billable string `json:"billable"`
	// 1 scored successfully (HTTP 200, billable). 2 input validation rejection (HTTP 400, not billable). 5 server-side error (HTTP 500 or 503, not billable). 6 no face detected (HTTP 200, billable). 7 multiple faces detected (HTTP 200, billable).
	StatusCode int32 `json:"status_code"`
	// Authenticity risk from 0.1 to 10.0, where higher means a higher likelihood of spoofing or AI generation. Null when the request was rejected or errored. Prefer `risk_level` for business rules, since band thresholds may be tuned.
	RiskScore NullableFloat32 `json:"risk_score"`
	// Risk band derived from `risk_score`: low is 0.1-3.9, medium is 4.0-6.9, high is 7.0-10.0. Null when the request was not scored.
	RiskLevel NullableString `json:"risk_level"`
	// Human-readable explanation of the result, safe to surface to end users.
	Message string `json:"message"`
	// Checks applied during analysis. Present only on scored responses.
	AiThreatSignals []string `json:"ai_threat_signals,omitempty"`
}

type _UnifiedFaceAuthenticityScore UnifiedFaceAuthenticityScore

// NewUnifiedFaceAuthenticityScore instantiates a new UnifiedFaceAuthenticityScore object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnifiedFaceAuthenticityScore(uniqueTrxId string, filename string, contentType string, status string, billable string, statusCode int32, riskScore NullableFloat32, riskLevel NullableString, message string) *UnifiedFaceAuthenticityScore {
	this := UnifiedFaceAuthenticityScore{}
	this.UniqueTrxId = uniqueTrxId
	this.Filename = filename
	this.ContentType = contentType
	this.Status = status
	this.Billable = billable
	this.StatusCode = statusCode
	this.RiskScore = riskScore
	this.RiskLevel = riskLevel
	this.Message = message
	return &this
}

// NewUnifiedFaceAuthenticityScoreWithDefaults instantiates a new UnifiedFaceAuthenticityScore object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnifiedFaceAuthenticityScoreWithDefaults() *UnifiedFaceAuthenticityScore {
	this := UnifiedFaceAuthenticityScore{}
	return &this
}

// GetUniqueTrxId returns the UniqueTrxId field value
func (o *UnifiedFaceAuthenticityScore) GetUniqueTrxId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UniqueTrxId
}

// GetUniqueTrxIdOk returns a tuple with the UniqueTrxId field value
// and a boolean to check if the value has been set.
func (o *UnifiedFaceAuthenticityScore) GetUniqueTrxIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UniqueTrxId, true
}

// SetUniqueTrxId sets field value
func (o *UnifiedFaceAuthenticityScore) SetUniqueTrxId(v string) {
	o.UniqueTrxId = v
}

// GetFilename returns the Filename field value
func (o *UnifiedFaceAuthenticityScore) GetFilename() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value
// and a boolean to check if the value has been set.
func (o *UnifiedFaceAuthenticityScore) GetFilenameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filename, true
}

// SetFilename sets field value
func (o *UnifiedFaceAuthenticityScore) SetFilename(v string) {
	o.Filename = v
}

// GetContentType returns the ContentType field value
func (o *UnifiedFaceAuthenticityScore) GetContentType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value
// and a boolean to check if the value has been set.
func (o *UnifiedFaceAuthenticityScore) GetContentTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentType, true
}

// SetContentType sets field value
func (o *UnifiedFaceAuthenticityScore) SetContentType(v string) {
	o.ContentType = v
}

// GetStatus returns the Status field value
func (o *UnifiedFaceAuthenticityScore) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UnifiedFaceAuthenticityScore) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UnifiedFaceAuthenticityScore) SetStatus(v string) {
	o.Status = v
}

// GetBillable returns the Billable field value
func (o *UnifiedFaceAuthenticityScore) GetBillable() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Billable
}

// GetBillableOk returns a tuple with the Billable field value
// and a boolean to check if the value has been set.
func (o *UnifiedFaceAuthenticityScore) GetBillableOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Billable, true
}

// SetBillable sets field value
func (o *UnifiedFaceAuthenticityScore) SetBillable(v string) {
	o.Billable = v
}

// GetStatusCode returns the StatusCode field value
func (o *UnifiedFaceAuthenticityScore) GetStatusCode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value
// and a boolean to check if the value has been set.
func (o *UnifiedFaceAuthenticityScore) GetStatusCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StatusCode, true
}

// SetStatusCode sets field value
func (o *UnifiedFaceAuthenticityScore) SetStatusCode(v int32) {
	o.StatusCode = v
}

// GetRiskScore returns the RiskScore field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *UnifiedFaceAuthenticityScore) GetRiskScore() float32 {
	if o == nil || o.RiskScore.Get() == nil {
		var ret float32
		return ret
	}

	return *o.RiskScore.Get()
}

// GetRiskScoreOk returns a tuple with the RiskScore field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UnifiedFaceAuthenticityScore) GetRiskScoreOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RiskScore.Get(), o.RiskScore.IsSet()
}

// SetRiskScore sets field value
func (o *UnifiedFaceAuthenticityScore) SetRiskScore(v float32) {
	o.RiskScore.Set(&v)
}

// GetRiskLevel returns the RiskLevel field value
// If the value is explicit nil, the zero value for string will be returned
func (o *UnifiedFaceAuthenticityScore) GetRiskLevel() string {
	if o == nil || o.RiskLevel.Get() == nil {
		var ret string
		return ret
	}

	return *o.RiskLevel.Get()
}

// GetRiskLevelOk returns a tuple with the RiskLevel field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UnifiedFaceAuthenticityScore) GetRiskLevelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RiskLevel.Get(), o.RiskLevel.IsSet()
}

// SetRiskLevel sets field value
func (o *UnifiedFaceAuthenticityScore) SetRiskLevel(v string) {
	o.RiskLevel.Set(&v)
}

// GetMessage returns the Message field value
func (o *UnifiedFaceAuthenticityScore) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *UnifiedFaceAuthenticityScore) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *UnifiedFaceAuthenticityScore) SetMessage(v string) {
	o.Message = v
}

// GetAiThreatSignals returns the AiThreatSignals field value if set, zero value otherwise.
func (o *UnifiedFaceAuthenticityScore) GetAiThreatSignals() []string {
	if o == nil || IsNil(o.AiThreatSignals) {
		var ret []string
		return ret
	}
	return o.AiThreatSignals
}

// GetAiThreatSignalsOk returns a tuple with the AiThreatSignals field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnifiedFaceAuthenticityScore) GetAiThreatSignalsOk() ([]string, bool) {
	if o == nil || IsNil(o.AiThreatSignals) {
		return nil, false
	}
	return o.AiThreatSignals, true
}

// HasAiThreatSignals returns a boolean if a field has been set.
func (o *UnifiedFaceAuthenticityScore) HasAiThreatSignals() bool {
	if o != nil && !IsNil(o.AiThreatSignals) {
		return true
	}

	return false
}

// SetAiThreatSignals gets a reference to the given []string and assigns it to the AiThreatSignals field.
func (o *UnifiedFaceAuthenticityScore) SetAiThreatSignals(v []string) {
	o.AiThreatSignals = v
}

func (o UnifiedFaceAuthenticityScore) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnifiedFaceAuthenticityScore) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["unique_trx_id"] = o.UniqueTrxId
	toSerialize["filename"] = o.Filename
	toSerialize["content_type"] = o.ContentType
	toSerialize["status"] = o.Status
	toSerialize["billable"] = o.Billable
	toSerialize["status_code"] = o.StatusCode
	toSerialize["risk_score"] = o.RiskScore.Get()
	toSerialize["risk_level"] = o.RiskLevel.Get()
	toSerialize["message"] = o.Message
	if !IsNil(o.AiThreatSignals) {
		toSerialize["ai_threat_signals"] = o.AiThreatSignals
	}
	return toSerialize, nil
}

func (o *UnifiedFaceAuthenticityScore) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"unique_trx_id",
		"filename",
		"content_type",
		"status",
		"billable",
		"status_code",
		"risk_score",
		"risk_level",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUnifiedFaceAuthenticityScore := _UnifiedFaceAuthenticityScore{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUnifiedFaceAuthenticityScore)

	if err != nil {
		return err
	}

	*o = UnifiedFaceAuthenticityScore(varUnifiedFaceAuthenticityScore)

	return err
}

type NullableUnifiedFaceAuthenticityScore struct {
	value *UnifiedFaceAuthenticityScore
	isSet bool
}

func (v NullableUnifiedFaceAuthenticityScore) Get() *UnifiedFaceAuthenticityScore {
	return v.value
}

func (v *NullableUnifiedFaceAuthenticityScore) Set(val *UnifiedFaceAuthenticityScore) {
	v.value = val
	v.isSet = true
}

func (v NullableUnifiedFaceAuthenticityScore) IsSet() bool {
	return v.isSet
}

func (v *NullableUnifiedFaceAuthenticityScore) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnifiedFaceAuthenticityScore(val *UnifiedFaceAuthenticityScore) *NullableUnifiedFaceAuthenticityScore {
	return &NullableUnifiedFaceAuthenticityScore{value: val, isSet: true}
}

func (v NullableUnifiedFaceAuthenticityScore) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnifiedFaceAuthenticityScore) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


