# coding: utf-8

"""
    NeuroVerify Detection API

    AI-generated and manipulated media detection for images and video.  NeuroVerify scores uploaded media for signs of spoofing and AI manipulation and returns an opaque risk score with a risk band, so you can accept, review, or reject without handling model internals.  **Authentication.** Send your API key in the `x-api-key` header on every request.  **Response envelopes.** Each endpoint wraps its result in a single named object, and that envelope is returned for successes, rejections, and errors alike. Read `status` and `status_code` to tell them apart rather than relying on the HTTP status code alone: a rejection for no face detected arrives as HTTP 200.  **Retries.** Retry HTTP 500 and 503 with exponential backoff, up to three attempts. Retry HTTP 429 after the interval given in `Retry-After`. Do not retry HTTP 400 or 401; correct the input or the key instead.

    The version of the OpenAPI document: 1.0.0
    Contact: support@neuraldefend.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBytes, StrictStr
from typing import Optional, Tuple, Union
from typing_extensions import Annotated
from neuraldefend._core.models.detect_video_response import DetectVideoResponse

from neuraldefend._core.api_client import ApiClient, RequestSerialized
from neuraldefend._core.api_response import ApiResponse
from neuraldefend._core.rest import RESTResponseType


class VideoAuthenticityApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def detect_video(
        self,
        file: Annotated[Union[StrictBytes, StrictStr, Tuple[StrictStr, StrictBytes]], Field(description="Video to analyze.")],
        max_frames: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Maximum number of frames to sample, from 1 to 100. Defaults to 12.")] = None,
        sample_rate: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Optional frame sampling override. Must be 1 or greater.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> DetectVideoResponse:
        """Score the authenticity of a video and its audio track

        Analyzes a video and returns independent risk scores for the video and audio modalities, each with its own risk band and message.  **Requirements.** MP4, AVI, MOV, MKV, WMV, FLV, WebM, OGG, or OGV. Maximum 1.5 GB. Frames are sampled uniformly, 12 by default. Frames containing several faces are skipped; if no single-face frames remain, the response is a rejection with `status_code: 6` on HTTP 200, and it is billable.  **Reading the result.** Video and audio are scored separately and no combined score is returned. Derive one client-side when you need it, for example max(video_risk_score, audio_risk_score or 0). Silent videos return null audio scores with `audio_message` set to \"No audio track detected\"; this is a success, not an error.  Every request produces a new `unique_trx_id`; requests are not idempotent.

        :param file: Video to analyze. (required)
        :type file: bytearray
        :param max_frames: Maximum number of frames to sample, from 1 to 100. Defaults to 12.
        :type max_frames: int
        :param sample_rate: Optional frame sampling override. Must be 1 or greater.
        :type sample_rate: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._detect_video_serialize(
            file=file,
            max_frames=max_frames,
            sample_rate=sample_rate,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "DetectVideoResponse",
            '400': "DetectVideoResponse",
            '401': "ApiError",
            '403': "ApiError",
            '429': "ApiError",
            '500': "DetectVideoResponse",
            '503': "DetectVideoResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def detect_video_with_http_info(
        self,
        file: Annotated[Union[StrictBytes, StrictStr, Tuple[StrictStr, StrictBytes]], Field(description="Video to analyze.")],
        max_frames: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Maximum number of frames to sample, from 1 to 100. Defaults to 12.")] = None,
        sample_rate: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Optional frame sampling override. Must be 1 or greater.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[DetectVideoResponse]:
        """Score the authenticity of a video and its audio track

        Analyzes a video and returns independent risk scores for the video and audio modalities, each with its own risk band and message.  **Requirements.** MP4, AVI, MOV, MKV, WMV, FLV, WebM, OGG, or OGV. Maximum 1.5 GB. Frames are sampled uniformly, 12 by default. Frames containing several faces are skipped; if no single-face frames remain, the response is a rejection with `status_code: 6` on HTTP 200, and it is billable.  **Reading the result.** Video and audio are scored separately and no combined score is returned. Derive one client-side when you need it, for example max(video_risk_score, audio_risk_score or 0). Silent videos return null audio scores with `audio_message` set to \"No audio track detected\"; this is a success, not an error.  Every request produces a new `unique_trx_id`; requests are not idempotent.

        :param file: Video to analyze. (required)
        :type file: bytearray
        :param max_frames: Maximum number of frames to sample, from 1 to 100. Defaults to 12.
        :type max_frames: int
        :param sample_rate: Optional frame sampling override. Must be 1 or greater.
        :type sample_rate: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._detect_video_serialize(
            file=file,
            max_frames=max_frames,
            sample_rate=sample_rate,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "DetectVideoResponse",
            '400': "DetectVideoResponse",
            '401': "ApiError",
            '403': "ApiError",
            '429': "ApiError",
            '500': "DetectVideoResponse",
            '503': "DetectVideoResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def detect_video_without_preload_content(
        self,
        file: Annotated[Union[StrictBytes, StrictStr, Tuple[StrictStr, StrictBytes]], Field(description="Video to analyze.")],
        max_frames: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Maximum number of frames to sample, from 1 to 100. Defaults to 12.")] = None,
        sample_rate: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Optional frame sampling override. Must be 1 or greater.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Score the authenticity of a video and its audio track

        Analyzes a video and returns independent risk scores for the video and audio modalities, each with its own risk band and message.  **Requirements.** MP4, AVI, MOV, MKV, WMV, FLV, WebM, OGG, or OGV. Maximum 1.5 GB. Frames are sampled uniformly, 12 by default. Frames containing several faces are skipped; if no single-face frames remain, the response is a rejection with `status_code: 6` on HTTP 200, and it is billable.  **Reading the result.** Video and audio are scored separately and no combined score is returned. Derive one client-side when you need it, for example max(video_risk_score, audio_risk_score or 0). Silent videos return null audio scores with `audio_message` set to \"No audio track detected\"; this is a success, not an error.  Every request produces a new `unique_trx_id`; requests are not idempotent.

        :param file: Video to analyze. (required)
        :type file: bytearray
        :param max_frames: Maximum number of frames to sample, from 1 to 100. Defaults to 12.
        :type max_frames: int
        :param sample_rate: Optional frame sampling override. Must be 1 or greater.
        :type sample_rate: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._detect_video_serialize(
            file=file,
            max_frames=max_frames,
            sample_rate=sample_rate,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "DetectVideoResponse",
            '400': "DetectVideoResponse",
            '401': "ApiError",
            '403': "ApiError",
            '429': "ApiError",
            '500': "DetectVideoResponse",
            '503': "DetectVideoResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _detect_video_serialize(
        self,
        file,
        max_frames,
        sample_rate,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if max_frames is not None:
            
            _query_params.append(('max_frames', max_frames))
            
        if sample_rate is not None:
            
            _query_params.append(('sample_rate', sample_rate))
            
        # process the header parameters
        # process the form parameters
        if file is not None:
            _files['file'] = file
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'multipart/form-data'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'ApiKeyAuth'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/detect/video',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


