# coding: utf-8

"""
    NeuroVerify Detection API

    AI-generated and manipulated media detection for images and video.  NeuroVerify scores uploaded media for signs of spoofing and AI manipulation and returns an opaque risk score with a risk band, so you can accept, review, or reject without handling model internals.  **Authentication.** Send your API key in the `x-api-key` header on every request.  **Response envelopes.** Each endpoint wraps its result in a single named object, and that envelope is returned for successes, rejections, and errors alike. Read `status` and `status_code` to tell them apart rather than relying on the HTTP status code alone: a rejection for no face detected arrives as HTTP 200.  **Retries.** Retry HTTP 500 and 503 with exponential backoff, up to three attempts. Retry HTTP 429 after the interval given in `Retry-After`. Do not retry HTTP 400 or 401; correct the input or the key instead.

    The version of the OpenAPI document: 1.0.0
    Contact: support@neuraldefend.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class UnifiedVideoAuthenticityScore(BaseModel):
    """
    Video authenticity result with independent video and audio risk scores. Derive an overall decision client-side, for example max(video_risk_score, audio_risk_score or 0).
    """ # noqa: E501
    unique_trx_id: StrictStr = Field(description="Unique transaction identifier. Store it for audit trail correlation and dispute resolution.")
    filename: StrictStr = Field(description="Name of the uploaded file, as received.")
    content_type: StrictStr = Field(description="MIME type detected for the uploaded file.")
    status: StrictStr = Field(description="Outcome of the request. `success` means the file was scored. `rejected` means the file did not pass pre-analysis validation and was not scored. `error` means a server-side failure prevented analysis.")
    billable: StrictStr = Field(description="`Y` when the request counts toward billing, `N` otherwise.")
    status_code: StrictInt = Field(description="1 scored successfully (HTTP 200, billable). 2 input validation rejection (HTTP 400, not billable). 5 server-side error (HTTP 500 or 503, not billable). 6 no scorable single-face frames (HTTP 200, billable).")
    video_risk_score: Optional[Union[Annotated[float, Field(le=10.0, strict=True, ge=0.1)], Annotated[int, Field(le=10, strict=True, ge=1)]]] = Field(description="Video modality risk from 0.1 to 10.0, where higher means a higher likelihood of AI manipulation. Null when the request was rejected or errored.")
    video_risk_level: Optional[StrictStr] = Field(description="Video risk band: low is 0.1-3.9, medium is 4.0-6.9, high is 7.0-10.0. Null when the video was not scored.")
    video_message: StrictStr = Field(description="Human-readable explanation for the video modality. Rejection and error copy is carried on this field.")
    audio_risk_score: Optional[Union[Annotated[float, Field(le=10.0, strict=True, ge=0.1)], Annotated[int, Field(le=10, strict=True, ge=1)]]] = Field(description="Audio modality risk from 0.1 to 10.0. Null when the video has no audio track, or when audio analysis was skipped or failed.")
    audio_risk_level: Optional[StrictStr] = Field(description="Audio risk band, using the same thresholds as video. Null when the audio was not scored.")
    audio_message: Optional[StrictStr] = Field(description="Human-readable explanation for the audio modality, such as \"No audio track detected\". Null on rejected requests.")
    ai_threat_signals: Optional[List[StrictStr]] = Field(default=None, description="Checks applied during analysis. Present only on scored responses.")
    __properties: ClassVar[List[str]] = ["unique_trx_id", "filename", "content_type", "status", "billable", "status_code", "video_risk_score", "video_risk_level", "video_message", "audio_risk_score", "audio_risk_level", "audio_message", "ai_threat_signals"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['success', 'rejected', 'error']):
            raise ValueError("must be one of enum values ('success', 'rejected', 'error')")
        return value

    @field_validator('billable')
    def billable_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['Y', 'N']):
            raise ValueError("must be one of enum values ('Y', 'N')")
        return value

    @field_validator('status_code')
    def status_code_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set([1, 2, 5, 6]):
            raise ValueError("must be one of enum values (1, 2, 5, 6)")
        return value

    @field_validator('video_risk_level')
    def video_risk_level_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['low', 'medium', 'high']):
            raise ValueError("must be one of enum values ('low', 'medium', 'high')")
        return value

    @field_validator('audio_risk_level')
    def audio_risk_level_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['low', 'medium', 'high']):
            raise ValueError("must be one of enum values ('low', 'medium', 'high')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UnifiedVideoAuthenticityScore from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if video_risk_score (nullable) is None
        # and model_fields_set contains the field
        if self.video_risk_score is None and "video_risk_score" in self.model_fields_set:
            _dict['video_risk_score'] = None

        # set to None if video_risk_level (nullable) is None
        # and model_fields_set contains the field
        if self.video_risk_level is None and "video_risk_level" in self.model_fields_set:
            _dict['video_risk_level'] = None

        # set to None if audio_risk_score (nullable) is None
        # and model_fields_set contains the field
        if self.audio_risk_score is None and "audio_risk_score" in self.model_fields_set:
            _dict['audio_risk_score'] = None

        # set to None if audio_risk_level (nullable) is None
        # and model_fields_set contains the field
        if self.audio_risk_level is None and "audio_risk_level" in self.model_fields_set:
            _dict['audio_risk_level'] = None

        # set to None if audio_message (nullable) is None
        # and model_fields_set contains the field
        if self.audio_message is None and "audio_message" in self.model_fields_set:
            _dict['audio_message'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UnifiedVideoAuthenticityScore from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "unique_trx_id": obj.get("unique_trx_id"),
            "filename": obj.get("filename"),
            "content_type": obj.get("content_type"),
            "status": obj.get("status"),
            "billable": obj.get("billable"),
            "status_code": obj.get("status_code"),
            "video_risk_score": obj.get("video_risk_score"),
            "video_risk_level": obj.get("video_risk_level"),
            "video_message": obj.get("video_message"),
            "audio_risk_score": obj.get("audio_risk_score"),
            "audio_risk_level": obj.get("audio_risk_level"),
            "audio_message": obj.get("audio_message"),
            "ai_threat_signals": obj.get("ai_threat_signals")
        })
        return _obj


