/*
 * NeuroVerify Detection API
 * AI-generated and manipulated media detection for images and video.  NeuroVerify scores uploaded media for signs of spoofing and AI manipulation and returns an opaque risk score with a risk band, so you can accept, review, or reject without handling model internals.  **Authentication.** Send your API key in the `x-api-key` header on every request.  **Response envelopes.** Each endpoint wraps its result in a single named object, and that envelope is returned for successes, rejections, and errors alike. Read `status` and `status_code` to tell them apart rather than relying on the HTTP status code alone: a rejection for no face detected arrives as HTTP 200.  **Retries.** Retry HTTP 500 and 503 with exponential backoff, up to three attempts. Retry HTTP 429 after the interval given in `Retry-After`. Do not retry HTTP 400 or 401; correct the input or the key instead.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@neuraldefend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.neuraldefend.internal.core;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.neuraldefend.internal.core.UnifiedFaceAuthenticityScore;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.neuraldefend.internal.core.ApiClient;
/**
 * Envelope returned by POST /detect/image for every outcome.
 */
@JsonPropertyOrder({
  DetectImageResponse.JSON_PROPERTY_UNIFIED_FACE_AUTHENTICITY_SCORE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class DetectImageResponse {
  public static final String JSON_PROPERTY_UNIFIED_FACE_AUTHENTICITY_SCORE = "unified_face_authenticity_score";
  @javax.annotation.Nonnull
  private UnifiedFaceAuthenticityScore unifiedFaceAuthenticityScore;

  public DetectImageResponse() { 
  }

  public DetectImageResponse unifiedFaceAuthenticityScore(@javax.annotation.Nonnull UnifiedFaceAuthenticityScore unifiedFaceAuthenticityScore) {
    this.unifiedFaceAuthenticityScore = unifiedFaceAuthenticityScore;
    return this;
  }

  /**
   * Get unifiedFaceAuthenticityScore
   * @return unifiedFaceAuthenticityScore
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_UNIFIED_FACE_AUTHENTICITY_SCORE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UnifiedFaceAuthenticityScore getUnifiedFaceAuthenticityScore() {
    return unifiedFaceAuthenticityScore;
  }


  @JsonProperty(JSON_PROPERTY_UNIFIED_FACE_AUTHENTICITY_SCORE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUnifiedFaceAuthenticityScore(@javax.annotation.Nonnull UnifiedFaceAuthenticityScore unifiedFaceAuthenticityScore) {
    this.unifiedFaceAuthenticityScore = unifiedFaceAuthenticityScore;
  }


  /**
   * Return true if this DetectImageResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DetectImageResponse detectImageResponse = (DetectImageResponse) o;
    return Objects.equals(this.unifiedFaceAuthenticityScore, detectImageResponse.unifiedFaceAuthenticityScore);
  }

  @Override
  public int hashCode() {
    return Objects.hash(unifiedFaceAuthenticityScore);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DetectImageResponse {\n");
    sb.append("    unifiedFaceAuthenticityScore: ").append(toIndentedString(unifiedFaceAuthenticityScore)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `unified_face_authenticity_score` to the URL query string
    if (getUnifiedFaceAuthenticityScore() != null) {
      joiner.add(getUnifiedFaceAuthenticityScore().toUrlQueryString(prefix + "unified_face_authenticity_score" + suffix));
    }

    return joiner.toString();
  }
}

