/*
 * NeuroVerify Detection API
 * AI-generated and manipulated media detection for images and video.  NeuroVerify scores uploaded media for signs of spoofing and AI manipulation and returns an opaque risk score with a risk band, so you can accept, review, or reject without handling model internals.  **Authentication.** Send your API key in the `x-api-key` header on every request.  **Response envelopes.** Each endpoint wraps its result in a single named object, and that envelope is returned for successes, rejections, and errors alike. Read `status` and `status_code` to tell them apart rather than relying on the HTTP status code alone: a rejection for no face detected arrives as HTTP 200.  **Retries.** Retry HTTP 500 and 503 with exponential backoff, up to three attempts. Retry HTTP 429 after the interval given in `Retry-After`. Do not retry HTTP 400 or 401; correct the input or the key instead.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@neuraldefend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.neuraldefend.internal.core;

import java.time.Instant;
import java.time.OffsetDateTime;
import java.time.ZonedDateTime;

import com.fasterxml.jackson.databind.module.SimpleModule;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class RFC3339JavaTimeModule extends SimpleModule {
    private static final long serialVersionUID = 1L;

    public RFC3339JavaTimeModule() {
        super("RFC3339JavaTimeModule");

        addDeserializer(Instant.class, RFC3339InstantDeserializer.INSTANT);
        addDeserializer(OffsetDateTime.class, RFC3339InstantDeserializer.OFFSET_DATE_TIME);
        addDeserializer(ZonedDateTime.class, RFC3339InstantDeserializer.ZONED_DATE_TIME);
    }
}
