/*
 * NeuroVerify Detection API
 * AI-generated and manipulated media detection for images and video.  NeuroVerify scores uploaded media for signs of spoofing and AI manipulation and returns an opaque risk score with a risk band, so you can accept, review, or reject without handling model internals.  **Authentication.** Send your API key in the `x-api-key` header on every request.  **Response envelopes.** Each endpoint wraps its result in a single named object, and that envelope is returned for successes, rejections, and errors alike. Read `status` and `status_code` to tell them apart rather than relying on the HTTP status code alone: a rejection for no face detected arrives as HTTP 200.  **Retries.** Retry HTTP 500 and 503 with exponential backoff, up to three attempts. Retry HTTP 429 after the interval given in `Retry-After`. Do not retry HTTP 400 or 401; correct the input or the key instead.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@neuraldefend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.neuraldefend.internal.core;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.neuraldefend.internal.core.ApiClient;
/**
 * Video authenticity result with independent video and audio risk scores. Derive an overall decision client-side, for example max(video_risk_score, audio_risk_score or 0).
 */
@JsonPropertyOrder({
  UnifiedVideoAuthenticityScore.JSON_PROPERTY_UNIQUE_TRX_ID,
  UnifiedVideoAuthenticityScore.JSON_PROPERTY_FILENAME,
  UnifiedVideoAuthenticityScore.JSON_PROPERTY_CONTENT_TYPE,
  UnifiedVideoAuthenticityScore.JSON_PROPERTY_STATUS,
  UnifiedVideoAuthenticityScore.JSON_PROPERTY_BILLABLE,
  UnifiedVideoAuthenticityScore.JSON_PROPERTY_STATUS_CODE,
  UnifiedVideoAuthenticityScore.JSON_PROPERTY_VIDEO_RISK_SCORE,
  UnifiedVideoAuthenticityScore.JSON_PROPERTY_VIDEO_RISK_LEVEL,
  UnifiedVideoAuthenticityScore.JSON_PROPERTY_VIDEO_MESSAGE,
  UnifiedVideoAuthenticityScore.JSON_PROPERTY_AUDIO_RISK_SCORE,
  UnifiedVideoAuthenticityScore.JSON_PROPERTY_AUDIO_RISK_LEVEL,
  UnifiedVideoAuthenticityScore.JSON_PROPERTY_AUDIO_MESSAGE,
  UnifiedVideoAuthenticityScore.JSON_PROPERTY_AI_THREAT_SIGNALS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class UnifiedVideoAuthenticityScore {
  public static final String JSON_PROPERTY_UNIQUE_TRX_ID = "unique_trx_id";
  @javax.annotation.Nonnull
  private String uniqueTrxId;

  public static final String JSON_PROPERTY_FILENAME = "filename";
  @javax.annotation.Nonnull
  private String filename;

  public static final String JSON_PROPERTY_CONTENT_TYPE = "content_type";
  @javax.annotation.Nonnull
  private String contentType;

  /**
   * Outcome of the request. &#x60;success&#x60; means the file was scored. &#x60;rejected&#x60; means the file did not pass pre-analysis validation and was not scored. &#x60;error&#x60; means a server-side failure prevented analysis.
   */
  public enum StatusEnum {
    SUCCESS(String.valueOf("success")),
    
    REJECTED(String.valueOf("rejected")),
    
    ERROR(String.valueOf("error"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nonnull
  private StatusEnum status;

  /**
   * &#x60;Y&#x60; when the request counts toward billing, &#x60;N&#x60; otherwise.
   */
  public enum BillableEnum {
    Y(String.valueOf("Y")),
    
    N(String.valueOf("N"));

    private String value;

    BillableEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static BillableEnum fromValue(String value) {
      for (BillableEnum b : BillableEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_BILLABLE = "billable";
  @javax.annotation.Nonnull
  private BillableEnum billable;

  /**
   * 1 scored successfully (HTTP 200, billable). 2 input validation rejection (HTTP 400, not billable). 5 server-side error (HTTP 500 or 503, not billable). 6 no scorable single-face frames (HTTP 200, billable).
   */
  public enum StatusCodeEnum {
    NUMBER_1(Integer.valueOf(1)),
    
    NUMBER_2(Integer.valueOf(2)),
    
    NUMBER_5(Integer.valueOf(5)),
    
    NUMBER_6(Integer.valueOf(6));

    private Integer value;

    StatusCodeEnum(Integer value) {
      this.value = value;
    }

    @JsonValue
    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusCodeEnum fromValue(Integer value) {
      for (StatusCodeEnum b : StatusCodeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS_CODE = "status_code";
  @javax.annotation.Nonnull
  private StatusCodeEnum statusCode;

  public static final String JSON_PROPERTY_VIDEO_RISK_SCORE = "video_risk_score";
  @javax.annotation.Nullable
  private Float videoRiskScore;

  /**
   * Video risk band: low is 0.1-3.9, medium is 4.0-6.9, high is 7.0-10.0. Null when the video was not scored.
   */
  public enum VideoRiskLevelEnum {
    LOW(String.valueOf("low")),
    
    MEDIUM(String.valueOf("medium")),
    
    HIGH(String.valueOf("high"));

    private String value;

    VideoRiskLevelEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static VideoRiskLevelEnum fromValue(String value) {
      for (VideoRiskLevelEnum b : VideoRiskLevelEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  public static final String JSON_PROPERTY_VIDEO_RISK_LEVEL = "video_risk_level";
  @javax.annotation.Nullable
  private VideoRiskLevelEnum videoRiskLevel;

  public static final String JSON_PROPERTY_VIDEO_MESSAGE = "video_message";
  @javax.annotation.Nonnull
  private String videoMessage;

  public static final String JSON_PROPERTY_AUDIO_RISK_SCORE = "audio_risk_score";
  @javax.annotation.Nullable
  private Float audioRiskScore;

  /**
   * Audio risk band, using the same thresholds as video. Null when the audio was not scored.
   */
  public enum AudioRiskLevelEnum {
    LOW(String.valueOf("low")),
    
    MEDIUM(String.valueOf("medium")),
    
    HIGH(String.valueOf("high"));

    private String value;

    AudioRiskLevelEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static AudioRiskLevelEnum fromValue(String value) {
      for (AudioRiskLevelEnum b : AudioRiskLevelEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  public static final String JSON_PROPERTY_AUDIO_RISK_LEVEL = "audio_risk_level";
  @javax.annotation.Nullable
  private AudioRiskLevelEnum audioRiskLevel;

  public static final String JSON_PROPERTY_AUDIO_MESSAGE = "audio_message";
  @javax.annotation.Nullable
  private String audioMessage;

  public static final String JSON_PROPERTY_AI_THREAT_SIGNALS = "ai_threat_signals";
  @javax.annotation.Nullable
  private List<String> aiThreatSignals = new ArrayList<>();

  public UnifiedVideoAuthenticityScore() { 
  }

  public UnifiedVideoAuthenticityScore uniqueTrxId(@javax.annotation.Nonnull String uniqueTrxId) {
    this.uniqueTrxId = uniqueTrxId;
    return this;
  }

  /**
   * Unique transaction identifier. Store it for audit trail correlation and dispute resolution.
   * @return uniqueTrxId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_UNIQUE_TRX_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getUniqueTrxId() {
    return uniqueTrxId;
  }


  @JsonProperty(JSON_PROPERTY_UNIQUE_TRX_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUniqueTrxId(@javax.annotation.Nonnull String uniqueTrxId) {
    this.uniqueTrxId = uniqueTrxId;
  }


  public UnifiedVideoAuthenticityScore filename(@javax.annotation.Nonnull String filename) {
    this.filename = filename;
    return this;
  }

  /**
   * Name of the uploaded file, as received.
   * @return filename
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FILENAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getFilename() {
    return filename;
  }


  @JsonProperty(JSON_PROPERTY_FILENAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFilename(@javax.annotation.Nonnull String filename) {
    this.filename = filename;
  }


  public UnifiedVideoAuthenticityScore contentType(@javax.annotation.Nonnull String contentType) {
    this.contentType = contentType;
    return this;
  }

  /**
   * MIME type detected for the uploaded file.
   * @return contentType
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CONTENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getContentType() {
    return contentType;
  }


  @JsonProperty(JSON_PROPERTY_CONTENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContentType(@javax.annotation.Nonnull String contentType) {
    this.contentType = contentType;
  }


  public UnifiedVideoAuthenticityScore status(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Outcome of the request. &#x60;success&#x60; means the file was scored. &#x60;rejected&#x60; means the file did not pass pre-analysis validation and was not scored. &#x60;error&#x60; means a server-side failure prevented analysis.
   * @return status
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }


  public UnifiedVideoAuthenticityScore billable(@javax.annotation.Nonnull BillableEnum billable) {
    this.billable = billable;
    return this;
  }

  /**
   * &#x60;Y&#x60; when the request counts toward billing, &#x60;N&#x60; otherwise.
   * @return billable
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_BILLABLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public BillableEnum getBillable() {
    return billable;
  }


  @JsonProperty(JSON_PROPERTY_BILLABLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBillable(@javax.annotation.Nonnull BillableEnum billable) {
    this.billable = billable;
  }


  public UnifiedVideoAuthenticityScore statusCode(@javax.annotation.Nonnull StatusCodeEnum statusCode) {
    this.statusCode = statusCode;
    return this;
  }

  /**
   * 1 scored successfully (HTTP 200, billable). 2 input validation rejection (HTTP 400, not billable). 5 server-side error (HTTP 500 or 503, not billable). 6 no scorable single-face frames (HTTP 200, billable).
   * @return statusCode
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATUS_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public StatusCodeEnum getStatusCode() {
    return statusCode;
  }


  @JsonProperty(JSON_PROPERTY_STATUS_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatusCode(@javax.annotation.Nonnull StatusCodeEnum statusCode) {
    this.statusCode = statusCode;
  }


  public UnifiedVideoAuthenticityScore videoRiskScore(@javax.annotation.Nullable Float videoRiskScore) {
    this.videoRiskScore = videoRiskScore;
    return this;
  }

  /**
   * Video modality risk from 0.1 to 10.0, where higher means a higher likelihood of AI manipulation. Null when the request was rejected or errored.
   * minimum: 0.1
   * maximum: 10.0
   * @return videoRiskScore
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VIDEO_RISK_SCORE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Float getVideoRiskScore() {
    return videoRiskScore;
  }


  @JsonProperty(JSON_PROPERTY_VIDEO_RISK_SCORE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVideoRiskScore(@javax.annotation.Nullable Float videoRiskScore) {
    this.videoRiskScore = videoRiskScore;
  }


  public UnifiedVideoAuthenticityScore videoRiskLevel(@javax.annotation.Nullable VideoRiskLevelEnum videoRiskLevel) {
    this.videoRiskLevel = videoRiskLevel;
    return this;
  }

  /**
   * Video risk band: low is 0.1-3.9, medium is 4.0-6.9, high is 7.0-10.0. Null when the video was not scored.
   * @return videoRiskLevel
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VIDEO_RISK_LEVEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public VideoRiskLevelEnum getVideoRiskLevel() {
    return videoRiskLevel;
  }


  @JsonProperty(JSON_PROPERTY_VIDEO_RISK_LEVEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVideoRiskLevel(@javax.annotation.Nullable VideoRiskLevelEnum videoRiskLevel) {
    this.videoRiskLevel = videoRiskLevel;
  }


  public UnifiedVideoAuthenticityScore videoMessage(@javax.annotation.Nonnull String videoMessage) {
    this.videoMessage = videoMessage;
    return this;
  }

  /**
   * Human-readable explanation for the video modality. Rejection and error copy is carried on this field.
   * @return videoMessage
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VIDEO_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getVideoMessage() {
    return videoMessage;
  }


  @JsonProperty(JSON_PROPERTY_VIDEO_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVideoMessage(@javax.annotation.Nonnull String videoMessage) {
    this.videoMessage = videoMessage;
  }


  public UnifiedVideoAuthenticityScore audioRiskScore(@javax.annotation.Nullable Float audioRiskScore) {
    this.audioRiskScore = audioRiskScore;
    return this;
  }

  /**
   * Audio modality risk from 0.1 to 10.0. Null when the video has no audio track, or when audio analysis was skipped or failed.
   * minimum: 0.1
   * maximum: 10.0
   * @return audioRiskScore
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AUDIO_RISK_SCORE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Float getAudioRiskScore() {
    return audioRiskScore;
  }


  @JsonProperty(JSON_PROPERTY_AUDIO_RISK_SCORE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAudioRiskScore(@javax.annotation.Nullable Float audioRiskScore) {
    this.audioRiskScore = audioRiskScore;
  }


  public UnifiedVideoAuthenticityScore audioRiskLevel(@javax.annotation.Nullable AudioRiskLevelEnum audioRiskLevel) {
    this.audioRiskLevel = audioRiskLevel;
    return this;
  }

  /**
   * Audio risk band, using the same thresholds as video. Null when the audio was not scored.
   * @return audioRiskLevel
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AUDIO_RISK_LEVEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public AudioRiskLevelEnum getAudioRiskLevel() {
    return audioRiskLevel;
  }


  @JsonProperty(JSON_PROPERTY_AUDIO_RISK_LEVEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAudioRiskLevel(@javax.annotation.Nullable AudioRiskLevelEnum audioRiskLevel) {
    this.audioRiskLevel = audioRiskLevel;
  }


  public UnifiedVideoAuthenticityScore audioMessage(@javax.annotation.Nullable String audioMessage) {
    this.audioMessage = audioMessage;
    return this;
  }

  /**
   * Human-readable explanation for the audio modality, such as \&quot;No audio track detected\&quot;. Null on rejected requests.
   * @return audioMessage
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AUDIO_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAudioMessage() {
    return audioMessage;
  }


  @JsonProperty(JSON_PROPERTY_AUDIO_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAudioMessage(@javax.annotation.Nullable String audioMessage) {
    this.audioMessage = audioMessage;
  }


  public UnifiedVideoAuthenticityScore aiThreatSignals(@javax.annotation.Nullable List<String> aiThreatSignals) {
    this.aiThreatSignals = aiThreatSignals;
    return this;
  }

  public UnifiedVideoAuthenticityScore addAiThreatSignalsItem(String aiThreatSignalsItem) {
    if (this.aiThreatSignals == null) {
      this.aiThreatSignals = new ArrayList<>();
    }
    this.aiThreatSignals.add(aiThreatSignalsItem);
    return this;
  }

  /**
   * Checks applied during analysis. Present only on scored responses.
   * @return aiThreatSignals
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AI_THREAT_SIGNALS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getAiThreatSignals() {
    return aiThreatSignals;
  }


  @JsonProperty(JSON_PROPERTY_AI_THREAT_SIGNALS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAiThreatSignals(@javax.annotation.Nullable List<String> aiThreatSignals) {
    this.aiThreatSignals = aiThreatSignals;
  }


  /**
   * Return true if this UnifiedVideoAuthenticityScore object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UnifiedVideoAuthenticityScore unifiedVideoAuthenticityScore = (UnifiedVideoAuthenticityScore) o;
    return Objects.equals(this.uniqueTrxId, unifiedVideoAuthenticityScore.uniqueTrxId) &&
        Objects.equals(this.filename, unifiedVideoAuthenticityScore.filename) &&
        Objects.equals(this.contentType, unifiedVideoAuthenticityScore.contentType) &&
        Objects.equals(this.status, unifiedVideoAuthenticityScore.status) &&
        Objects.equals(this.billable, unifiedVideoAuthenticityScore.billable) &&
        Objects.equals(this.statusCode, unifiedVideoAuthenticityScore.statusCode) &&
        Objects.equals(this.videoRiskScore, unifiedVideoAuthenticityScore.videoRiskScore) &&
        Objects.equals(this.videoRiskLevel, unifiedVideoAuthenticityScore.videoRiskLevel) &&
        Objects.equals(this.videoMessage, unifiedVideoAuthenticityScore.videoMessage) &&
        Objects.equals(this.audioRiskScore, unifiedVideoAuthenticityScore.audioRiskScore) &&
        Objects.equals(this.audioRiskLevel, unifiedVideoAuthenticityScore.audioRiskLevel) &&
        Objects.equals(this.audioMessage, unifiedVideoAuthenticityScore.audioMessage) &&
        Objects.equals(this.aiThreatSignals, unifiedVideoAuthenticityScore.aiThreatSignals);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uniqueTrxId, filename, contentType, status, billable, statusCode, videoRiskScore, videoRiskLevel, videoMessage, audioRiskScore, audioRiskLevel, audioMessage, aiThreatSignals);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UnifiedVideoAuthenticityScore {\n");
    sb.append("    uniqueTrxId: ").append(toIndentedString(uniqueTrxId)).append("\n");
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    billable: ").append(toIndentedString(billable)).append("\n");
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("    videoRiskScore: ").append(toIndentedString(videoRiskScore)).append("\n");
    sb.append("    videoRiskLevel: ").append(toIndentedString(videoRiskLevel)).append("\n");
    sb.append("    videoMessage: ").append(toIndentedString(videoMessage)).append("\n");
    sb.append("    audioRiskScore: ").append(toIndentedString(audioRiskScore)).append("\n");
    sb.append("    audioRiskLevel: ").append(toIndentedString(audioRiskLevel)).append("\n");
    sb.append("    audioMessage: ").append(toIndentedString(audioMessage)).append("\n");
    sb.append("    aiThreatSignals: ").append(toIndentedString(aiThreatSignals)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `unique_trx_id` to the URL query string
    if (getUniqueTrxId() != null) {
      joiner.add(String.format("%sunique_trx_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUniqueTrxId()))));
    }

    // add `filename` to the URL query string
    if (getFilename() != null) {
      joiner.add(String.format("%sfilename%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFilename()))));
    }

    // add `content_type` to the URL query string
    if (getContentType() != null) {
      joiner.add(String.format("%scontent_type%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContentType()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format("%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `billable` to the URL query string
    if (getBillable() != null) {
      joiner.add(String.format("%sbillable%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBillable()))));
    }

    // add `status_code` to the URL query string
    if (getStatusCode() != null) {
      joiner.add(String.format("%sstatus_code%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatusCode()))));
    }

    // add `video_risk_score` to the URL query string
    if (getVideoRiskScore() != null) {
      joiner.add(String.format("%svideo_risk_score%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVideoRiskScore()))));
    }

    // add `video_risk_level` to the URL query string
    if (getVideoRiskLevel() != null) {
      joiner.add(String.format("%svideo_risk_level%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVideoRiskLevel()))));
    }

    // add `video_message` to the URL query string
    if (getVideoMessage() != null) {
      joiner.add(String.format("%svideo_message%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVideoMessage()))));
    }

    // add `audio_risk_score` to the URL query string
    if (getAudioRiskScore() != null) {
      joiner.add(String.format("%saudio_risk_score%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAudioRiskScore()))));
    }

    // add `audio_risk_level` to the URL query string
    if (getAudioRiskLevel() != null) {
      joiner.add(String.format("%saudio_risk_level%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAudioRiskLevel()))));
    }

    // add `audio_message` to the URL query string
    if (getAudioMessage() != null) {
      joiner.add(String.format("%saudio_message%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAudioMessage()))));
    }

    // add `ai_threat_signals` to the URL query string
    if (getAiThreatSignals() != null) {
      for (int i = 0; i < getAiThreatSignals().size(); i++) {
        joiner.add(String.format("%sai_threat_signals%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getAiThreatSignals().get(i)))));
      }
    }

    return joiner.toString();
  }
}

