/* tslint:disable */
/* eslint-disable */
/**
 * NeuroVerify Detection API
 * AI-generated and manipulated media detection for images and video.  NeuroVerify scores uploaded media for signs of spoofing and AI manipulation and returns an opaque risk score with a risk band, so you can accept, review, or reject without handling model internals.  **Authentication.** Send your API key in the `x-api-key` header on every request.  **Response envelopes.** Each endpoint wraps its result in a single named object, and that envelope is returned for successes, rejections, and errors alike. Read `status` and `status_code` to tell them apart rather than relying on the HTTP status code alone: a rejection for no face detected arrives as HTTP 200.  **Retries.** Retry HTTP 500 and 503 with exponential backoff, up to three attempts. Retry HTTP 429 after the interval given in `Retry-After`. Do not retry HTTP 400 or 401; correct the input or the key instead.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@neuraldefend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Authentication, authorization, and rate limit failures.
 * @export
 * @interface ApiError
 */
export interface ApiError {
    /**
     * Reason the request was refused.
     * @type {string}
     * @memberof ApiError
     */
    detail: string;
}

/**
 * Check if a given object implements the ApiError interface.
 */
export function instanceOfApiError(value: object): value is ApiError {
    if (!('detail' in value) || value['detail'] === undefined) return false;
    return true;
}

export function ApiErrorFromJSON(json: any): ApiError {
    return ApiErrorFromJSONTyped(json, false);
}

export function ApiErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiError {
    if (json == null) {
        return json;
    }
    return {
        
        'detail': json['detail'],
    };
}

export function ApiErrorToJSON(json: any): ApiError {
    return ApiErrorToJSONTyped(json, false);
}

export function ApiErrorToJSONTyped(value?: ApiError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'detail': value['detail'],
    };
}

