/* tslint:disable */
/* eslint-disable */
/**
 * NeuroVerify Detection API
 * AI-generated and manipulated media detection for images and video.  NeuroVerify scores uploaded media for signs of spoofing and AI manipulation and returns an opaque risk score with a risk band, so you can accept, review, or reject without handling model internals.  **Authentication.** Send your API key in the `x-api-key` header on every request.  **Response envelopes.** Each endpoint wraps its result in a single named object, and that envelope is returned for successes, rejections, and errors alike. Read `status` and `status_code` to tell them apart rather than relying on the HTTP status code alone: a rejection for no face detected arrives as HTTP 200.  **Retries.** Retry HTTP 500 and 503 with exponential backoff, up to three attempts. Retry HTTP 429 after the interval given in `Retry-After`. Do not retry HTTP 400 or 401; correct the input or the key instead.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@neuraldefend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UnifiedVideoAuthenticityScore } from './UnifiedVideoAuthenticityScore';
import {
    UnifiedVideoAuthenticityScoreFromJSON,
    UnifiedVideoAuthenticityScoreFromJSONTyped,
    UnifiedVideoAuthenticityScoreToJSON,
    UnifiedVideoAuthenticityScoreToJSONTyped,
} from './UnifiedVideoAuthenticityScore';

/**
 * Envelope returned by POST /detect/video for every outcome.
 * @export
 * @interface DetectVideoResponse
 */
export interface DetectVideoResponse {
    /**
     * 
     * @type {UnifiedVideoAuthenticityScore}
     * @memberof DetectVideoResponse
     */
    unifiedVideoAuthenticityScore: UnifiedVideoAuthenticityScore;
}

/**
 * Check if a given object implements the DetectVideoResponse interface.
 */
export function instanceOfDetectVideoResponse(value: object): value is DetectVideoResponse {
    if (!('unifiedVideoAuthenticityScore' in value) || value['unifiedVideoAuthenticityScore'] === undefined) return false;
    return true;
}

export function DetectVideoResponseFromJSON(json: any): DetectVideoResponse {
    return DetectVideoResponseFromJSONTyped(json, false);
}

export function DetectVideoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetectVideoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'unifiedVideoAuthenticityScore': UnifiedVideoAuthenticityScoreFromJSON(json['unified_video_authenticity_score']),
    };
}

export function DetectVideoResponseToJSON(json: any): DetectVideoResponse {
    return DetectVideoResponseToJSONTyped(json, false);
}

export function DetectVideoResponseToJSONTyped(value?: DetectVideoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'unified_video_authenticity_score': UnifiedVideoAuthenticityScoreToJSON(value['unifiedVideoAuthenticityScore']),
    };
}

