/* tslint:disable */
/* eslint-disable */
/**
 * NeuroVerify Detection API
 * AI-generated and manipulated media detection for images and video.  NeuroVerify scores uploaded media for signs of spoofing and AI manipulation and returns an opaque risk score with a risk band, so you can accept, review, or reject without handling model internals.  **Authentication.** Send your API key in the `x-api-key` header on every request.  **Response envelopes.** Each endpoint wraps its result in a single named object, and that envelope is returned for successes, rejections, and errors alike. Read `status` and `status_code` to tell them apart rather than relying on the HTTP status code alone: a rejection for no face detected arrives as HTTP 200.  **Retries.** Retry HTTP 500 and 503 with exponential backoff, up to three attempts. Retry HTTP 429 after the interval given in `Retry-After`. Do not retry HTTP 400 or 401; correct the input or the key instead.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@neuraldefend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Face authenticity result for a single uploaded image.
 * @export
 * @interface UnifiedFaceAuthenticityScore
 */
export interface UnifiedFaceAuthenticityScore {
    /**
     * Unique transaction identifier. Store it for audit trail correlation and dispute resolution.
     * @type {string}
     * @memberof UnifiedFaceAuthenticityScore
     */
    uniqueTrxId: string;
    /**
     * Name of the uploaded file, as received.
     * @type {string}
     * @memberof UnifiedFaceAuthenticityScore
     */
    filename: string;
    /**
     * MIME type detected for the uploaded file.
     * @type {string}
     * @memberof UnifiedFaceAuthenticityScore
     */
    contentType: string;
    /**
     * Outcome of the request. `success` means the file was scored. `rejected` means the file did not pass pre-analysis validation and was not scored. `error` means a server-side failure prevented analysis.
     * @type {string}
     * @memberof UnifiedFaceAuthenticityScore
     */
    status: UnifiedFaceAuthenticityScoreStatusEnum;
    /**
     * `Y` when the request counts toward billing, `N` otherwise.
     * @type {string}
     * @memberof UnifiedFaceAuthenticityScore
     */
    billable: UnifiedFaceAuthenticityScoreBillableEnum;
    /**
     * 1 scored successfully (HTTP 200, billable). 2 input validation rejection (HTTP 400, not billable). 5 server-side error (HTTP 500 or 503, not billable). 6 no face detected (HTTP 200, billable). 7 multiple faces detected (HTTP 200, billable).
     * @type {number}
     * @memberof UnifiedFaceAuthenticityScore
     */
    statusCode: UnifiedFaceAuthenticityScoreStatusCodeEnum;
    /**
     * Authenticity risk from 0.1 to 10.0, where higher means a higher likelihood of spoofing or AI generation. Null when the request was rejected or errored. Prefer `risk_level` for business rules, since band thresholds may be tuned.
     * @type {number}
     * @memberof UnifiedFaceAuthenticityScore
     */
    riskScore: number | null;
    /**
     * Risk band derived from `risk_score`: low is 0.1-3.9, medium is 4.0-6.9, high is 7.0-10.0. Null when the request was not scored.
     * @type {string}
     * @memberof UnifiedFaceAuthenticityScore
     */
    riskLevel: UnifiedFaceAuthenticityScoreRiskLevelEnum | null;
    /**
     * Human-readable explanation of the result, safe to surface to end users.
     * @type {string}
     * @memberof UnifiedFaceAuthenticityScore
     */
    message: string;
    /**
     * Checks applied during analysis. Present only on scored responses.
     * @type {Array<string>}
     * @memberof UnifiedFaceAuthenticityScore
     */
    aiThreatSignals?: Array<string>;
}


/**
 * @export
 */
export const UnifiedFaceAuthenticityScoreStatusEnum = {
    Success: 'success',
    Rejected: 'rejected',
    Error: 'error'
} as const;
export type UnifiedFaceAuthenticityScoreStatusEnum = typeof UnifiedFaceAuthenticityScoreStatusEnum[keyof typeof UnifiedFaceAuthenticityScoreStatusEnum];

/**
 * @export
 */
export const UnifiedFaceAuthenticityScoreBillableEnum = {
    Y: 'Y',
    N: 'N'
} as const;
export type UnifiedFaceAuthenticityScoreBillableEnum = typeof UnifiedFaceAuthenticityScoreBillableEnum[keyof typeof UnifiedFaceAuthenticityScoreBillableEnum];

/**
 * @export
 */
export const UnifiedFaceAuthenticityScoreStatusCodeEnum = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_5: 5,
    NUMBER_6: 6,
    NUMBER_7: 7
} as const;
export type UnifiedFaceAuthenticityScoreStatusCodeEnum = typeof UnifiedFaceAuthenticityScoreStatusCodeEnum[keyof typeof UnifiedFaceAuthenticityScoreStatusCodeEnum];

/**
 * @export
 */
export const UnifiedFaceAuthenticityScoreRiskLevelEnum = {
    Low: 'low',
    Medium: 'medium',
    High: 'high'
} as const;
export type UnifiedFaceAuthenticityScoreRiskLevelEnum = typeof UnifiedFaceAuthenticityScoreRiskLevelEnum[keyof typeof UnifiedFaceAuthenticityScoreRiskLevelEnum];


/**
 * Check if a given object implements the UnifiedFaceAuthenticityScore interface.
 */
export function instanceOfUnifiedFaceAuthenticityScore(value: object): value is UnifiedFaceAuthenticityScore {
    if (!('uniqueTrxId' in value) || value['uniqueTrxId'] === undefined) return false;
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if (!('contentType' in value) || value['contentType'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('billable' in value) || value['billable'] === undefined) return false;
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('riskScore' in value) || value['riskScore'] === undefined) return false;
    if (!('riskLevel' in value) || value['riskLevel'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function UnifiedFaceAuthenticityScoreFromJSON(json: any): UnifiedFaceAuthenticityScore {
    return UnifiedFaceAuthenticityScoreFromJSONTyped(json, false);
}

export function UnifiedFaceAuthenticityScoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnifiedFaceAuthenticityScore {
    if (json == null) {
        return json;
    }
    return {
        
        'uniqueTrxId': json['unique_trx_id'],
        'filename': json['filename'],
        'contentType': json['content_type'],
        'status': json['status'],
        'billable': json['billable'],
        'statusCode': json['status_code'],
        'riskScore': json['risk_score'],
        'riskLevel': json['risk_level'],
        'message': json['message'],
        'aiThreatSignals': json['ai_threat_signals'] == null ? undefined : json['ai_threat_signals'],
    };
}

export function UnifiedFaceAuthenticityScoreToJSON(json: any): UnifiedFaceAuthenticityScore {
    return UnifiedFaceAuthenticityScoreToJSONTyped(json, false);
}

export function UnifiedFaceAuthenticityScoreToJSONTyped(value?: UnifiedFaceAuthenticityScore | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'unique_trx_id': value['uniqueTrxId'],
        'filename': value['filename'],
        'content_type': value['contentType'],
        'status': value['status'],
        'billable': value['billable'],
        'status_code': value['statusCode'],
        'risk_score': value['riskScore'],
        'risk_level': value['riskLevel'],
        'message': value['message'],
        'ai_threat_signals': value['aiThreatSignals'],
    };
}

