/* tslint:disable */
/* eslint-disable */
/**
 * NeuroVerify Detection API
 * AI-generated and manipulated media detection for images and video.  NeuroVerify scores uploaded media for signs of spoofing and AI manipulation and returns an opaque risk score with a risk band, so you can accept, review, or reject without handling model internals.  **Authentication.** Send your API key in the `x-api-key` header on every request.  **Response envelopes.** Each endpoint wraps its result in a single named object, and that envelope is returned for successes, rejections, and errors alike. Read `status` and `status_code` to tell them apart rather than relying on the HTTP status code alone: a rejection for no face detected arrives as HTTP 200.  **Retries.** Retry HTTP 500 and 503 with exponential backoff, up to three attempts. Retry HTTP 429 after the interval given in `Retry-After`. Do not retry HTTP 400 or 401; correct the input or the key instead.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@neuraldefend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Video authenticity result with independent video and audio risk scores. Derive an overall decision client-side, for example max(video_risk_score, audio_risk_score or 0).
 * @export
 * @interface UnifiedVideoAuthenticityScore
 */
export interface UnifiedVideoAuthenticityScore {
    /**
     * Unique transaction identifier. Store it for audit trail correlation and dispute resolution.
     * @type {string}
     * @memberof UnifiedVideoAuthenticityScore
     */
    uniqueTrxId: string;
    /**
     * Name of the uploaded file, as received.
     * @type {string}
     * @memberof UnifiedVideoAuthenticityScore
     */
    filename: string;
    /**
     * MIME type detected for the uploaded file.
     * @type {string}
     * @memberof UnifiedVideoAuthenticityScore
     */
    contentType: string;
    /**
     * Outcome of the request. `success` means the file was scored. `rejected` means the file did not pass pre-analysis validation and was not scored. `error` means a server-side failure prevented analysis.
     * @type {string}
     * @memberof UnifiedVideoAuthenticityScore
     */
    status: UnifiedVideoAuthenticityScoreStatusEnum;
    /**
     * `Y` when the request counts toward billing, `N` otherwise.
     * @type {string}
     * @memberof UnifiedVideoAuthenticityScore
     */
    billable: UnifiedVideoAuthenticityScoreBillableEnum;
    /**
     * 1 scored successfully (HTTP 200, billable). 2 input validation rejection (HTTP 400, not billable). 5 server-side error (HTTP 500 or 503, not billable). 6 no scorable single-face frames (HTTP 200, billable).
     * @type {number}
     * @memberof UnifiedVideoAuthenticityScore
     */
    statusCode: UnifiedVideoAuthenticityScoreStatusCodeEnum;
    /**
     * Video modality risk from 0.1 to 10.0, where higher means a higher likelihood of AI manipulation. Null when the request was rejected or errored.
     * @type {number}
     * @memberof UnifiedVideoAuthenticityScore
     */
    videoRiskScore: number | null;
    /**
     * Video risk band: low is 0.1-3.9, medium is 4.0-6.9, high is 7.0-10.0. Null when the video was not scored.
     * @type {string}
     * @memberof UnifiedVideoAuthenticityScore
     */
    videoRiskLevel: UnifiedVideoAuthenticityScoreVideoRiskLevelEnum | null;
    /**
     * Human-readable explanation for the video modality. Rejection and error copy is carried on this field.
     * @type {string}
     * @memberof UnifiedVideoAuthenticityScore
     */
    videoMessage: string;
    /**
     * Audio modality risk from 0.1 to 10.0. Null when the video has no audio track, or when audio analysis was skipped or failed.
     * @type {number}
     * @memberof UnifiedVideoAuthenticityScore
     */
    audioRiskScore: number | null;
    /**
     * Audio risk band, using the same thresholds as video. Null when the audio was not scored.
     * @type {string}
     * @memberof UnifiedVideoAuthenticityScore
     */
    audioRiskLevel: UnifiedVideoAuthenticityScoreAudioRiskLevelEnum | null;
    /**
     * Human-readable explanation for the audio modality, such as "No audio track detected". Null on rejected requests.
     * @type {string}
     * @memberof UnifiedVideoAuthenticityScore
     */
    audioMessage: string | null;
    /**
     * Checks applied during analysis. Present only on scored responses.
     * @type {Array<string>}
     * @memberof UnifiedVideoAuthenticityScore
     */
    aiThreatSignals?: Array<string>;
}


/**
 * @export
 */
export const UnifiedVideoAuthenticityScoreStatusEnum = {
    Success: 'success',
    Rejected: 'rejected',
    Error: 'error'
} as const;
export type UnifiedVideoAuthenticityScoreStatusEnum = typeof UnifiedVideoAuthenticityScoreStatusEnum[keyof typeof UnifiedVideoAuthenticityScoreStatusEnum];

/**
 * @export
 */
export const UnifiedVideoAuthenticityScoreBillableEnum = {
    Y: 'Y',
    N: 'N'
} as const;
export type UnifiedVideoAuthenticityScoreBillableEnum = typeof UnifiedVideoAuthenticityScoreBillableEnum[keyof typeof UnifiedVideoAuthenticityScoreBillableEnum];

/**
 * @export
 */
export const UnifiedVideoAuthenticityScoreStatusCodeEnum = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_5: 5,
    NUMBER_6: 6
} as const;
export type UnifiedVideoAuthenticityScoreStatusCodeEnum = typeof UnifiedVideoAuthenticityScoreStatusCodeEnum[keyof typeof UnifiedVideoAuthenticityScoreStatusCodeEnum];

/**
 * @export
 */
export const UnifiedVideoAuthenticityScoreVideoRiskLevelEnum = {
    Low: 'low',
    Medium: 'medium',
    High: 'high'
} as const;
export type UnifiedVideoAuthenticityScoreVideoRiskLevelEnum = typeof UnifiedVideoAuthenticityScoreVideoRiskLevelEnum[keyof typeof UnifiedVideoAuthenticityScoreVideoRiskLevelEnum];

/**
 * @export
 */
export const UnifiedVideoAuthenticityScoreAudioRiskLevelEnum = {
    Low: 'low',
    Medium: 'medium',
    High: 'high'
} as const;
export type UnifiedVideoAuthenticityScoreAudioRiskLevelEnum = typeof UnifiedVideoAuthenticityScoreAudioRiskLevelEnum[keyof typeof UnifiedVideoAuthenticityScoreAudioRiskLevelEnum];


/**
 * Check if a given object implements the UnifiedVideoAuthenticityScore interface.
 */
export function instanceOfUnifiedVideoAuthenticityScore(value: object): value is UnifiedVideoAuthenticityScore {
    if (!('uniqueTrxId' in value) || value['uniqueTrxId'] === undefined) return false;
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if (!('contentType' in value) || value['contentType'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('billable' in value) || value['billable'] === undefined) return false;
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('videoRiskScore' in value) || value['videoRiskScore'] === undefined) return false;
    if (!('videoRiskLevel' in value) || value['videoRiskLevel'] === undefined) return false;
    if (!('videoMessage' in value) || value['videoMessage'] === undefined) return false;
    if (!('audioRiskScore' in value) || value['audioRiskScore'] === undefined) return false;
    if (!('audioRiskLevel' in value) || value['audioRiskLevel'] === undefined) return false;
    if (!('audioMessage' in value) || value['audioMessage'] === undefined) return false;
    return true;
}

export function UnifiedVideoAuthenticityScoreFromJSON(json: any): UnifiedVideoAuthenticityScore {
    return UnifiedVideoAuthenticityScoreFromJSONTyped(json, false);
}

export function UnifiedVideoAuthenticityScoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnifiedVideoAuthenticityScore {
    if (json == null) {
        return json;
    }
    return {
        
        'uniqueTrxId': json['unique_trx_id'],
        'filename': json['filename'],
        'contentType': json['content_type'],
        'status': json['status'],
        'billable': json['billable'],
        'statusCode': json['status_code'],
        'videoRiskScore': json['video_risk_score'],
        'videoRiskLevel': json['video_risk_level'],
        'videoMessage': json['video_message'],
        'audioRiskScore': json['audio_risk_score'],
        'audioRiskLevel': json['audio_risk_level'],
        'audioMessage': json['audio_message'],
        'aiThreatSignals': json['ai_threat_signals'] == null ? undefined : json['ai_threat_signals'],
    };
}

export function UnifiedVideoAuthenticityScoreToJSON(json: any): UnifiedVideoAuthenticityScore {
    return UnifiedVideoAuthenticityScoreToJSONTyped(json, false);
}

export function UnifiedVideoAuthenticityScoreToJSONTyped(value?: UnifiedVideoAuthenticityScore | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'unique_trx_id': value['uniqueTrxId'],
        'filename': value['filename'],
        'content_type': value['contentType'],
        'status': value['status'],
        'billable': value['billable'],
        'status_code': value['statusCode'],
        'video_risk_score': value['videoRiskScore'],
        'video_risk_level': value['videoRiskLevel'],
        'video_message': value['videoMessage'],
        'audio_risk_score': value['audioRiskScore'],
        'audio_risk_level': value['audioRiskLevel'],
        'audio_message': value['audioMessage'],
        'ai_threat_signals': value['aiThreatSignals'],
    };
}

