# coding: utf-8

# flake8: noqa

"""
    NeuroVerify Detection API

    AI-generated and manipulated media detection for images and video.  NeuroVerify scores uploaded media for signs of spoofing and AI manipulation and returns an opaque risk score with a risk band, so you can accept, review, or reject without handling model internals.  **Authentication.** Send your API key in the `x-api-key` header on every request.  **Response envelopes.** Each endpoint wraps its result in a single named object, and that envelope is returned for successes, rejections, and errors alike. Read `status` and `status_code` to tell them apart rather than relying on the HTTP status code alone: a rejection for no face detected arrives as HTTP 200.  **Retries.** Retry HTTP 500 and 503 with exponential backoff, up to three attempts. Retry HTTP 429 after the interval given in `Retry-After`. Do not retry HTTP 400 or 401; correct the input or the key instead.

    The version of the OpenAPI document: 1.0.0
    Contact: support@neuraldefend.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "ImageAuthenticityApi",
    "VideoAuthenticityApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ApiError",
    "DetectImageResponse",
    "DetectVideoResponse",
    "UnifiedFaceAuthenticityScore",
    "UnifiedVideoAuthenticityScore",
]

# import apis into sdk package
from neuraldefend._core.api.image_authenticity_api import ImageAuthenticityApi as ImageAuthenticityApi
from neuraldefend._core.api.video_authenticity_api import VideoAuthenticityApi as VideoAuthenticityApi

# import ApiClient
from neuraldefend._core.api_response import ApiResponse as ApiResponse
from neuraldefend._core.api_client import ApiClient as ApiClient
from neuraldefend._core.configuration import Configuration as Configuration
from neuraldefend._core.exceptions import OpenApiException as OpenApiException
from neuraldefend._core.exceptions import ApiTypeError as ApiTypeError
from neuraldefend._core.exceptions import ApiValueError as ApiValueError
from neuraldefend._core.exceptions import ApiKeyError as ApiKeyError
from neuraldefend._core.exceptions import ApiAttributeError as ApiAttributeError
from neuraldefend._core.exceptions import ApiException as ApiException

# import models into sdk package
from neuraldefend._core.models.api_error import ApiError as ApiError
from neuraldefend._core.models.detect_image_response import DetectImageResponse as DetectImageResponse
from neuraldefend._core.models.detect_video_response import DetectVideoResponse as DetectVideoResponse
from neuraldefend._core.models.unified_face_authenticity_score import UnifiedFaceAuthenticityScore as UnifiedFaceAuthenticityScore
from neuraldefend._core.models.unified_video_authenticity_score import UnifiedVideoAuthenticityScore as UnifiedVideoAuthenticityScore
